# Generated by Django 2.2 on 2020-08-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200825_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=64, verbose_name='资产名称'),
        ),
    ]
